# Generated by Django 3.2.4 on 2021-06-28 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0002_auto_20210622_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Only active users are allowed to interact in the circle', verbose_name='active status'),
        ),
    ]
